---

- name: Assertions
  ansible.builtin.assert:
    that:
      - roundcube_docker_data is defined
      - roundcube_fqdn is defined

- name: Create location to export files to docker container from
  ansible.builtin.file:
    path: "{{ roundcube_docker_data }}"
    state: directory
    owner: root
    group: "{{ roundcube_docker_group | default('root') }}"
    mode: "0750"

- name: Copy OpenSSL Self-signed key + certificate
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    remote_src: true
  loop:
    - src: "{{ openssl_server_key }}"
      dest: "{{ roundcube_docker_data }}/privkey.pem"
      mode: "0600"
    - src: "{{ openssl_server_crt }}"
      dest: "{{ roundcube_docker_data }}/fullchain.pem"
  notify: Restart services
  when: openssl_server_key is defined and openssl_server_crt is defined

- name: Copy custom SSL certificate
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    remote_src: "{{ True if roundcube_ssl_key is search('^/') else False }}"
  loop:
    - src: "{{ roundcube_ssl_key }}"
      dest: "{{ roundcube_docker_data }}/privkey.pem"
      mode: "0600"
    - src: "{{ roundcube_ssl_certificate_chain }}"
      dest: "{{ roundcube_docker_data }}/fullchain.pem"
  notify: Restart services
  when: roundcube_ssl_key is defined and roundcube_ssl_certificate_chain is defined

- name: Create roundcube/nginx configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: templates/docker-compose.yml.j2
      dest: "{{ roundcube_docker_data }}/docker-compose.yml"
    - src: templates/nginx-roundcube.conf.j2
      dest: "{{ roundcube_docker_data }}/nginx-roundcube.conf"
    - src: templates/nginx-default.conf.j2
      dest: "{{ roundcube_docker_data }}/nginx-default.conf"
    - src: templates/nginx-ssl.conf.j2
      dest: "{{ roundcube_docker_data }}/nginx-ssl.conf"
    - src: templates/env.j2
      dest: "{{ roundcube_docker_data }}/.env"
  notify: Restart services
